# 连接数据库的信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC
    username: root
    password: 666888
    # 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
      pathmatch: # Springfox使用的路径匹配是基于AntPathMatcher的
        # 所以需要配置此参数
        matching-strategy: ant_path_matcher
# mybatis配置
mybatis:
  # 扫描映射文件
  mapper-locations: classpath:mapper/*.xml
  # 配置别名扫描的包(配置后，映射文件中的resultType中不需要写包名，直接写类名即可)
  type-aliases-package: com.lyx.model
  configuration:
    # 开启驼峰映射配置
    map-underscore-to-camel-case: true
# 打印执行过程的sql信息
logging:
  level:
    com.qf.mapper: DEBUG